resources:
  - name: source
    type: git
    source: &github
      uri: https://github.com/waterlink/books.git
      params:
        depth: 1
      branch: master

  - name: deploy-test
    type: cf
    source:
      api: {{pcf-apiurl}}
      username: {{pcf-username}}
      password: {{pcf-password}}
      organization: {{pcf-org}}
      space: Test

jobs:
  - name: deploy-backend-to-test
    plan:
    - get: source
      trigger: true
    - task: build-backend
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: { repository: openjdk }
        inputs:
        - name: source
        run:
          path: source/ci/scripts/build-backend.sh
        outputs:
        - name: backend-built
    - put: deploy-test
      params:
        current_app_name: books-backend-test
        manifest: source/backend/manifest-test.yml